#if !defined FAT_NAMESPACE_H
#define FAT_NAMESPACE_H

#include "FatConfig.h"

/**
 * @brief API tag
 */
#define FATAPI
#define TEST

#define IN
#define OUT
#define INTERNAL

#define SKIP_INDEX_OFFSET(_index) (_index + 1)
#define ARR_SIZEOF(_arr) (sizeof(_arr) / sizeof(*_arr))
#define UNI_SIZEOF(_uni, _type) (sizeof(_uni) / sizeof(_type))

#define VOID void
// #define NULL (FILE*)0
#define UINT8 unsigned char
#define UINT16 unsigned short
#define UINT32 unsigned int

#define CONST const
#define STATIC static

#define FAT_FIELD field_ft
#define FAT_BOOT_START boot_start_ft
#define FAT_BPB biospb_ft
#define FAT_FS_INFO fsinfo_ft
#define FAT_STATUS UINT8
#define FAT_FILE UINT8 *

#define BASE_FAT12 12
#define BASE_FAT16 16
#define BASE_FAT32 32

#define VOLUME_SIGNATURE_SZ 512

#define MAIL_NULL               0x00
#define MAIL_FIELD              0x01
#define MAIL_BROKEN_FIELD       0x02

#define RETURN(_what, ...) RETURN_ ## _what (__VA_ARGS__)
#define RETURN_STATUS(_status) RETURN_STATUS_ ## _status
#define RETURN_STATUS_OK                0x00
#define RETURN_STATUS_UNK_FAT_BASE      0x01
#define RETURN_STATUS_NOT_IMPLEMENTED   0x02
#define RETURN_FILE(_file) RETURN_FILE_ ## _file
#define RETURN_FILE_VPZ ((void*)0)

#define INTERNAL_FAT_SIGNATURE_NAME FatBuffer

#define INTERNAL_STRUCT_ID_FIELD(_name, _index, _size, _offset) \
    ._name = { \
        .field = &INTERNAL_FAT_SIGNATURE_NAME[_index], \
        .size = _size, \
        .offset = _offset, \
        .mail = MAIL_FIELD, \
    }

#define STRUCT_ID_FIELD(_field) \
    INTERNAL_STRUCT_ID_FIELD( \
        STRUCT_ID_ ## _field ## _NAME, \
        STRUCT_ID_ ## _field ## _IDX, \
        STRUCT_ID_ ## _field ## _SZ, \
        STRUCT_ID_ ## _field ## _OFFSET \
    )

#define STRUCT_ID_FIELD_NULL \
    ._NULL_ = { \
        .field = RETURN_FILE_VPZ, \
        .size = 0, \
        .offset = 0, \
        .mail = MAIL_NULL \
    }

#define STRUCT_ID_FATX_OFFSET           (0)

#define STRUCT_ID_JMPBOOT_NAME          jmpBoot
#define STRUCT_ID_JMPBOOT_IDX           (STRUCT_ID_FATX_OFFSET)
#define STRUCT_ID_JMPBOOT_SZ            (3)
#define STRUCT_ID_JMPBOOT_OFFSET        (STRUCT_ID_FATX_OFFSET + STRUCT_ID_JMPBOOT_SZ)

#define STRUCT_ID_OEMNAME_NAME          OEMName
#define STRUCT_ID_OEMNAME_IDX           (STRUCT_ID_JMPBOOT_OFFSET)
#define STRUCT_ID_OEMNAME_SZ            (8)
#define STRUCT_ID_OEMNAME_OFFSET        (STRUCT_ID_JMPBOOT_OFFSET + STRUCT_ID_OEMNAME_SZ)

#define STRUCT_ID_BYTSPERSEC_NAME       BytsPerSec
#define STRUCT_ID_BYTSPERSEC_IDX        (STRUCT_ID_OEMNAME_OFFSET)
#define STRUCT_ID_BYTSPERSEC_SZ         (2)
#define STRUCT_ID_BYTSPERSEC_OFFSET     (STRUCT_ID_OEMNAME_OFFSET + STRUCT_ID_BYTSPERSEC_SZ)

#define STRUCT_ID_SERPERCLUS_NAME       SerPerClus
#define STRUCT_ID_SERPERCLUS_IDX        (STRUCT_ID_BYTSPERSEC_OFFSET)
#define STRUCT_ID_SERPERCLUS_SZ         (1)
#define STRUCT_ID_SERPERCLUS_OFFSET     (STRUCT_ID_BYTSPERSEC_OFFSET + STRUCT_ID_SERPERCLUS_SZ)

#define STRUCT_ID_RSVDSECCNT_NAME       RsvdSecCnt
#define STRUCT_ID_RSVDSECCNT_IDX        (STRUCT_ID_SERPERCLUS_OFFSET)
#define STRUCT_ID_RSVDSECCNT_SZ         (2)
#define STRUCT_ID_RSVDSECCNT_OFFSET     (STRUCT_ID_SERPERCLUS_OFFSET + STRUCT_ID_RSVDSECCNT_SZ)

#define STRUCT_ID_NUMFATS_NAME          NumFATs
#define STRUCT_ID_NUMFATS_IDX           (STRUCT_ID_RSVDSECCNT_OFFSET)
#define STRUCT_ID_NUMFATS_SZ            (1)
#define STRUCT_ID_NUMFATS_OFFSET        (STRUCT_ID_RSVDSECCNT_OFFSET + STRUCT_ID_NUMFATS_SZ)

#define STRUCT_ID_ROOTENTCNT_NAME       RootEntCnt
#define STRUCT_ID_ROOTENTCNT_IDX        (STRUCT_ID_NUMFATS_OFFSET)
#define STRUCT_ID_ROOTENTCNT_SZ         (2)
#define STRUCT_ID_ROOTENTCNT_OFFSET     (STRUCT_ID_NUMFATS_OFFSET + STRUCT_ID_ROOTENTCNT_SZ)

#define STRUCT_ID_TOTSEC16_NAME         TotSec16
#define STRUCT_ID_TOTSEC16_IDX          (STRUCT_ID_ROOTENTCNT_OFFSET)
#define STRUCT_ID_TOTSEC16_SZ           (2)
#define STRUCT_ID_TOTSEC16_OFFSET       (STRUCT_ID_ROOTENTCNT_OFFSET + STRUCT_ID_ROOTENTCNT_SZ)

#define STRUCT_ID_MEDIA_NAME            Media
#define STRUCT_ID_MEDIA_IDX             (STRUCT_ID_TOTSEC16_OFFSET)
#define STRUCT_ID_MEDIA_SZ              (1)
#define STRUCT_ID_MEDIA_OFFSET          (STRUCT_ID_TOTSEC16_OFFSET + STRUCT_ID_MEDIA_SZ)

#define STRUCT_ID_FATSZ16_NAME          FATSz16
#define STRUCT_ID_FATSZ16_IDX           (STRUCT_ID_MEDIA_OFFSET)
#define STRUCT_ID_FATSZ16_SZ            (2)
#define STRUCT_ID_FATSZ16_OFFSET        (STRUCT_ID_MEDIA_OFFSET + STRUCT_ID_FATSZ16_SZ)

#define STRUCT_ID_SECPERTRK_NAME        SecPerTrk
#define STRUCT_ID_SECPERTRK_IDX         (STRUCT_ID_FATSZ16_OFFSET)
#define STRUCT_ID_SECPERTRK_SZ          (2)
#define STRUCT_ID_SECPERTRK_OFFSET      (STRUCT_ID_FATSZ16_OFFSET + STRUCT_ID_SECPERTRK_SZ)

#define STRUCT_ID_NUMHEADS_NAME         NumHeads
#define STRUCT_ID_NUMHEADS_IDX          (STRUCT_ID_SECPERTRK_OFFSET)
#define STRUCT_ID_NUMHEADS_SZ           (2)
#define STRUCT_ID_NUMHEADS_OFFSET       (STRUCT_ID_SECPERTRK_OFFSET + STRUCT_ID_NUMHEADS_SZ)

#define STRUCT_ID_HIDDSEC_NAME          HiddSec
#define STRUCT_ID_HIDDSEC_IDX           (STRUCT_ID_NUMHEADS_OFFSET)
#define STRUCT_ID_HIDDSEC_SZ            (4)
#define STRUCT_ID_HIDDSEC_OFFSET        (STRUCT_ID_NUMHEADS_OFFSET + STRUCT_ID_HIDDSEC_SZ)

#define STRUCT_ID_TOTSEC32_NAME         TotSec32
#define STRUCT_ID_TOTSEC32_IDX          (STRUCT_ID_HIDDSEC_OFFSET)
#define STRUCT_ID_TOTSEC32_SZ           (4)
#define STRUCT_ID_TOTSEC32_OFFSET       (STRUCT_ID_HIDDSEC_OFFSET + STRUCT_ID_TOTSEC32_SZ)

// stop

#if IS_FS_FATX == IS_FS_FAT32
#define STRUCT_ID_FATSZ32_NAME          FATSz32
#define STRUCT_ID_FATSZ32_IDX           (STRUCT_ID_TOTSEC32_OFFSET)
#define STRUCT_ID_FATSZ32_SZ            (4)
#define STRUCT_ID_FATSZ32_OFFSET        (STRUCT_ID_TOTSEC32_OFFSET + STRUCT_ID_FATSZ32_SZ)

#define STRUCT_ID_EXTFLAGS_NAME         ExtFlags
#define STRUCT_ID_EXTFLAGS_IDX          (STRUCT_ID_FATSZ32_OFFSET)
#define STRUCT_ID_EXTFLAGS_SZ           (2)
#define STRUCT_ID_EXTFLAGS_OFFSET       (STRUCT_ID_FATSZ32_OFFSET + STRUCT_ID_EXTFLAGS_SZ)

#define STRUCT_ID_FSVER_NAME            FSVer
#define STRUCT_ID_FSVER_IDX             (STRUCT_ID_EXTFLAGS_OFFSET)
#define STRUCT_ID_FSVER_SZ              (2)
#define STRUCT_ID_FSVER_OFFSET          (STRUCT_ID_EXTFLAGS_OFFSET + STRUCT_ID_FSVER_SZ)

#define STRUCT_ID_ROOTCLUS_NAME         RootClus
#define STRUCT_ID_ROOTCLUS_IDX          (STRUCT_ID_FSVER_OFFSET)
#define STRUCT_ID_ROOTCLUS_SZ           (4)
#define STRUCT_ID_ROOTCLUS_OFFSET       (STRUCT_ID_FSVER_OFFSET + STRUCT_ID_ROOTCLUS_SZ)

#define STRUCT_ID_FSINFO_NAME           FSInfo
#define STRUCT_ID_FSINFO_IDX            (STRUCT_ID_ROOTCLUS_OFFSET)
#define STRUCT_ID_FSINFO_SZ             (2)
#define STRUCT_ID_FSINFO_OFFSET         (STRUCT_ID_ROOTCLUS_OFFSET + STRUCT_ID_FSINFO_SZ)

#define STRUCT_ID_BKBOOTSEC_NAME        BkBootSec
#define STRUCT_ID_BKBOOTSEC_IDX         (STRUCT_ID_FSINFO_OFFSET)
#define STRUCT_ID_BKBOOTSEC_SZ          (2)
#define STRUCT_ID_BKBOOTSEC_OFFSET      (STRUCT_ID_FSINFO_OFFSET + STRUCT_ID_BKBOOTSEC_SZ)

#define STRUCT_ID_RESERVED0_NAME        Reserved
#define STRUCT_ID_RESERVED0_IDX         (STRUCT_ID_BKBOOTSEC_OFFSET)
#define STRUCT_ID_RESERVED0_SZ          (12)
#define STRUCT_ID_RESERVED0_OFFSET      (STRUCT_ID_BKBOOTSEC_OFFSET + STRUCT_ID_RESERVED0_SZ)

#define STRUCT_ID_DRVNUM_NAME           DrvNum
#define STRUCT_ID_DRVNUM_IDX            (STRUCT_ID_RESERVED0_OFFSET)
#define STRUCT_ID_DRVNUM_SZ             (1)
#define STRUCT_ID_DRVNUM_OFFSET         (STRUCT_ID_RESERVED0_OFFSET + STRUCT_ID_DRVNUM_SZ)

#else

#define STRUCT_ID_DRVNUM_NAME           DrvNum
#define STRUCT_ID_DRVNUM_IDX            (STRUCT_ID_TOTSEC32_OFFSET)
#define STRUCT_ID_DRVNUM_SZ             (1)
#define STRUCT_ID_DRVNUM_OFFSET         (STRUCT_ID_TOTSEC32_OFFSET + STRUCT_ID_FATSZ32_SZ)

#endif

#define STRUCT_ID_RESERVED1_NAME        Reserved1
#define STRUCT_ID_RESERVED1_IDX         (STRUCT_ID_DRVNUM_OFFSET)
#define STRUCT_ID_RESERVED1_SZ          (1)
#define STRUCT_ID_RESERVED1_OFFSET      (STRUCT_ID_DRVNUM_OFFSET + STRUCT_ID_RESERVED1_SZ)

#define STRUCT_ID_BOOTSIG_NAME          BootSig
#define STRUCT_ID_BOOTSIG_IDX           (STRUCT_ID_RESERVED1_OFFSET)
#define STRUCT_ID_BOOTSIG_SZ            (1)
#define STRUCT_ID_BOOTSIG_OFFSET        (STRUCT_ID_RESERVED1_OFFSET + STRUCT_ID_BOOTSIG_SZ)

#define STRUCT_ID_VOLID_NAME            VolID
#define STRUCT_ID_VOLID_IDX             (STRUCT_ID_BOOTSIG_OFFSET)
#define STRUCT_ID_VOLID_SZ              (4)
#define STRUCT_ID_VOLID_OFFSET          (STRUCT_ID_BOOTSIG_OFFSET + STRUCT_ID_VOLID_SZ)

#define STRUCT_ID_VOLLAB_NAME           VolLab
#define STRUCT_ID_VOLLAB_IDX            (STRUCT_ID_VOLID_OFFSET)
#define STRUCT_ID_VOLLAB_SZ             (11)
#define STRUCT_ID_VOLLAB_OFFSET         (STRUCT_ID_VOLID_OFFSET + STRUCT_ID_VOLLAB_SZ)

#define STRUCT_ID_FILSYSTYPE_NAME       FilSysType
#define STRUCT_ID_FILSYSTYPE_IDX        (STRUCT_ID_VOLLAB_OFFSET)
#define STRUCT_ID_FILSYSTYPE_SZ         (8)
#define STRUCT_ID_FILSYSTYPE_OFFSET     (STRUCT_ID_VOLLAB_OFFSET + STRUCT_ID_FILSYSTYPE_SZ)

#define STRUCT_ID_SETTOZERO1_NAME       SetToZero1
#define STRUCT_ID_SETTOZERO1_IDX        (STRUCT_ID_FILSYSTYPE_OFFSET)
#define STRUCT_ID_SETTOZERO1_SZ         (420)
#define STRUCT_ID_SETTOZERO1_OFFSET     (STRUCT_ID_FILSYSTYPE_OFFSET + STRUCT_ID_SETTOZERO1_SZ)

#define STRUCT_ID_SIGNATUREWORD_NAME    Signature_word
#define STRUCT_ID_SIGNATUREWORD_IDX     (STRUCT_ID_SETTOZERO1_OFFSET)
#define STRUCT_ID_SIGNATUREWORD_SZ      (2)
#define STRUCT_ID_SIGNATUREWORD_OFFSET  (STRUCT_ID_SETTOZERO1_OFFSET + STRUCT_ID_SIGNATUREWORD_SZ)

#define STRUCT_ID_SETTOZERO2_NAME       SetToZero2
#define STRUCT_ID_SETTOZERO2_IDX        (STRUCT_ID_SIGNATUREWORD_OFFSET)
#define STRUCT_ID_SETTOZERO2_SZ         (0)
#define STRUCT_ID_SETTOZERO2_OFFSET     (STRUCT_ID_SIGNATUREWORD_OFFSET + STRUCT_ID_SETTOZERO2_SZ)

#else
#error "This file cannot be reused"
#error "You can create the same namespace in another file"

#endif /* FAT_NAMESPACE_H */